
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 60
#define YY_END_OF_BUFFER 61
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[491] =
    {   0,
        0,    0,   61,   59,    1,    2,   38,   59,   59,   49,
       59,   59,   47,   45,   46,   48,    4,   40,   18,   39,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   20,   59,   21,   44,    0,
        8,    0,    0,    0,    0,   37,    0,    0,    4,    6,
        4,    0,   42,   57,    0,   43,   41,   58,   58,   58,
       54,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   36,    8,    0,    0,    0,    7,    5,    0,
       58,   58,   58,   58,   58,   58,   58,   58,   10,   58,

       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,    0,    0,    5,   58,
       58,   58,   58,    9,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,    0,    0,   58,   58,
       58,   58,   58,   58,   58,   58,   31,   58,   58,   58,
       58,   58,   58,   11,   58,   58,   13,   58,   58,   58,
        0,   58,   58,   58,   58,    0,    0,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       50,   58,   58,   58,   58,   58,    0,   58,   58,   58,

       58,    0,    0,    3,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   16,   58,   58,   58,   58,
       58,   58,    0,   58,   58,   58,   58,    0,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,    0,   58,   58,   58,   58,
       56,   58,   58,   58,   12,   58,   58,   58,   32,   53,
       14,   58,   58,   26,   15,   58,   17,   58,   58,    0,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,    0,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,

       58,    0,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   34,   58,   58,   58,   58,    0,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   35,   58,
       58,   58,    0,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,    0,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   24,   58,
        0,   58,   58,   58,   58,   58,   58,   28,   58,   58,
       58,   58,   58,    0,   58,   58,   23,   51,   58,   58,
       52,   58,   58,   58,   58,    0,   58,   58,   58,   58,
        0,   58,   58,   58,    0,   58,   58,   58,   58,   19,

       58,   58,   58,    0,   58,   58,   58,   58,   58,   58,
       58,    0,   58,   58,   58,   58,   58,   58,   58,    0,
       58,   58,   24,   58,   58,   58,   58,    0,   58,   58,
       58,   58,   58,   25,    0,   58,   58,   58,   58,   58,
        0,   58,   58,   58,   58,   58,    0,   58,   29,   22,
       27,   58,    0,   58,   58,    0,   58,   58,    0,   30,
       58,    0,   58,    0,   58,    0,   33,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   55,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,    1,   20,
       21,   22,    1,    1,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   32,   46,   32,
        1,    1,    1,    1,   47,    1,   48,   49,   50,   51,

       52,   53,   54,   55,   56,   32,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,   67,   68,   69,   32,
       70,   32,   71,   72,   73,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[74] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    1,    4,    1,
        3,    3,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[497] =
    {   0,
        0,    0,  975,  976,  976,  976,  953,   73,   70,  976,
      964,    0,  976,  976,  976,  976,   80,   81,  951,  950,
       70,   78,    0,   92,   70,   97,   86,   89,   77,  110,
      127,   81,  113,  124,   82,  976,  898,  976,  976,  963,
      976,  153,  208,   87,  123,  976,  958,  948,  214,  976,
      134,  134,  976,  976,  150,  976,  976,    0,  132,  142,
        0,  134,  150,  141,  171,  151,  189,  207,  195,  201,
      211,  198,  198,  220,  205,  219,  214,  208,  218,  235,
      217,  211,  976,  976,  960,  234,  244,  976,  265,  943,
      917,  916,  262,  263,  261,  915,  262,  251,    0,  914,

      260,  256,  256,  905,  259,  259,  265,  900,  266,  260,
      281,  264,  271,  283,  270,  895,  284,  291,  304,  307,
      301,  296,  306,    0,  298,  301,  890,  317,  313,  316,
      307,  323,  311,  314,  322,  328,  322,  312,  325,  325,
      885,  927,  338,  344,  347,  348,  361,  346,  344,  351,
      353,  361,  365,  882,  364,  367,    0,  361,  357,  373,
      368,  366,  377,    0,  366,  384,    0,  379,  881,  382,
      369,  880,  878,  378,  387,  384,  920,  392,  386,  873,
      407,  396,  401,  413,  406,  407,  403,  406,  415,  415,
        0,  404,  415,  422,  421,  420,  421,  424,  419,  871,

      426,  418,  914,  976,  446,  869,  442,  439,  867,  449,
      865,  449,  439,  459,  791,    0,  466,  463,  456,  466,
      458,  706,  455,  462,  471,  472,  460,  465,  467,  480,
      485,  481,  483,  661,  487,  491,  489,  487,  491,  486,
      498,  482,  513,  502,  498,  586,  503,  513,  506,  457,
      976,  519,  521,  447,    0,  525,  524,  520,    0,    0,
        0,  532,  521,    0,    0,  521,    0,  534,  541,  534,
      532,  444,  388,  538,  539,  539,  541,  354,  538,  543,
      564,  558,  549,  562,  338,  561,  572,  563,  577,  568,
      572,  301,  571,  578,  569,  585,  587,  574,  591,  577,

      580,  599,  298,  586,  593,  589,  594,  592,  602,  593,
      258,  208,    0,  614,  606,  615,  619,  605,  626,  619,
      622,  623,  200,  635,  627,  639,  628,  628,    0,  197,
      637,  625,  235,  635,  631,  638,  645,  644,  640,  658,
      655,  667,  663,  656,  658,  160,  658,  159,  666,  666,
      668,  662,  682,  668,  676,  678,  157,  687,    0,  676,
      689,  676,  154,  691,  696,  686,  700,    0,  693,  704,
      690,  702,  703,  714,  706,  713,    0,    0,  706,  153,
        0,  188,  718,  726,  150,  192,  711,  720,  148,  729,
      180,  727,  144,  735,  736,  141,  728,  743,  732,  976,

      733,  734,  743,  756,  756,  756,  752,  139,  757,  758,
      766,  756,  766,  138,  769,  771,  761,  775,  764,  776,
      776,  770,    0,  776,  788,  786,  789,  165,  785,  797,
      798,  799,  789,    0,  794,  796,  787,  810,  805,  118,
      812,  814,  806,  822,  816,  812,  154,   77,    0,    0,
        0,  827,  816,  828,  831,  831,  828,  843,  829,    0,
      830,  835,  841,  839,  836,  851,    0,  839,  105,  111,
      835,  846,  844,  109,  844,  859,  859,  106,  860,  858,
      101,  854,  865,  863,   72,  882,  878,  883,  976,  976,
      935,  940,  943,  945,  950,  955

    } ;

static yyconst flex_int16_t yy_def[497] =
    {   0,
      490,    1,  490,  490,  490,  490,  490,  491,  490,  490,
      490,  492,  490,  490,  490,  490,  490,  493,  490,  490,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  490,  490,  490,  490,  495,
      490,  495,  491,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  493,  490,  490,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  490,  490,  495,  490,  490,  490,  490,  490,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,

      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  490,  490,  490,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  490,  490,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      490,  494,  494,  494,  494,  490,  496,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  490,  494,  494,  494,

      494,  490,  496,  490,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  490,  494,  494,  494,  494,  490,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  490,  494,  494,  494,  494,
      490,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  490,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  490,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,

      494,  490,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  490,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  490,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  490,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      490,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  490,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  490,  494,  494,  494,  494,
      490,  494,  494,  494,  490,  494,  494,  494,  494,  490,

      494,  494,  494,  490,  494,  494,  494,  494,  494,  494,
      494,  490,  494,  494,  494,  494,  494,  494,  494,  490,
      494,  494,  494,  494,  494,  494,  494,  490,  494,  494,
      494,  494,  494,  494,  490,  494,  494,  494,  494,  494,
      490,  494,  494,  494,  494,  494,  490,  494,  494,  494,
      494,  494,  490,  494,  494,  490,  494,  494,  490,  494,
      494,  490,  494,  490,  494,  490,  494,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,    0,
      490,  490,  490,  490,  490,  490

    } ;

static yyconst flex_int16_t yy_nxt[1050] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
        4,    4,   13,   14,    4,   15,    4,   16,   17,   18,
       19,   20,   21,   22,   23,   23,   23,   24,   23,   25,
       26,   23,   23,   27,   28,   29,   23,   23,   23,   23,
       30,   31,   32,   33,   34,   35,   23,   21,   22,   23,
       23,   23,   24,   23,   25,   26,   23,   27,   28,   29,
       23,   23,   23,   23,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   40,   40,  486,   40,   40,   41,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   42,
       40,   40,   40,   40,   40,   44,   48,   52,   49,   45,

       62,   53,   54,   59,  482,   60,   67,   50,   70,  479,
       61,   71,  475,   72,  471,   51,   78,   63,   82,  470,
       44,   68,   64,  454,   45,   62,   86,   59,   65,   60,
       67,   66,   50,   70,   61,   79,   71,   72,   69,   51,
       78,   63,   82,   40,   40,   40,   68,   64,   73,   75,
       86,   74,   65,   80,   81,   66,   76,  453,   84,   87,
       79,   50,   69,   90,  446,   91,   52,   92,  435,   77,
      490,   54,   73,   93,   75,   74,   94,   97,   80,   81,
       95,   76,   85,   87,  422,  416,   50,  405,   90,   91,
      402,  400,   92,   77,  398,  395,  394,   93,  391,  390,

      376,   94,   97,  371,   95,  362,  360,   85,   40,   40,
       96,   40,   40,   41,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   42,   40,   40,   40,   40,   40,
       48,   98,   49,   99,   96,  100,  101,  102,  347,  104,
      105,   50,  106,  344,  107,  108,  338,  109,  110,   51,
      103,  111,  115,  116,  328,   98,  117,  112,   99,  100,
      101,  113,  102,  104,  105,  114,   50,  106,  107,  118,
      108,  109,  110,   51,  103,  111,  115,  116,   40,   40,
       40,  117,  112,   89,  122,  123,  113,  124,  127,  134,
      114,  128,   50,  136,  118,  130,  131,  132,  135,  138,

      119,  125,  139,  140,  327,  141,  142,  143,  147,  122,
      123,  145,  124,  127,  134,  128,  144,   50,  136,  130,
      131,  132,  135,  138,  119,  125,  139,  148,  140,  141,
      142,   50,  143,  147,  149,  145,  150,  152,  153,  154,
      144,  151,  155,  157,  319,  158,  159,  308,  160,  161,
      165,  148,  162,  163,  164,  166,   50,  167,  168,  149,
      150,  152,  153,  154,  169,  151,  155,  172,  157,  158,
      173,  159,  160,  174,  161,  165,  162,  163,  164,  166,
      175,  167,  168,  176,  301,  177,  178,  179,  169,  180,
      181,  182,  172,  184,  185,  173,  186,  187,  174,  188,

      294,  189,  190,  191,  175,  192,  193,  196,  176,  177,
      178,  179,  194,  180,  197,  181,  182,  200,  184,  185,
      186,  187,  201,  202,  188,  189,  190,  205,  191,  192,
      206,  193,  196,  208,  289,  209,  194,  210,  197,  211,
      217,  200,  212,  213,  214,  215,  201,  202,  216,  218,
      219,  205,  220,  224,  206,  221,  222,  223,  208,  209,
      225,  210,  227,  228,  211,  217,  212,  213,  214,  215,
      229,  231,  216,  218,  219,  232,  234,  220,  224,  221,
      222,  223,  236,  237,  225,  238,  227,  228,  240,  241,
      288,  242,  243,  277,  244,  229,  231,  246,  247,  232,

      248,  234,  249,  274,  250,  251,  236,  237,  252,  253,
      238,  254,  266,  240,  241,  242,  255,  243,  244,  256,
      258,  246,  247,  259,  260,  248,  261,  249,  250,  251,
      262,  264,  252,  265,  253,  263,  254,  266,  267,  272,
      255,  268,  269,  256,  258,  271,  273,  259,  260,  275,
      261,  276,  278,  279,  262,  264,  280,  265,  281,  263,
      282,  283,  284,  267,  272,  268,  269,  285,  295,  271,
      273,  286,  287,  290,  275,  291,  276,  278,  279,  292,
      280,  293,  296,  281,  282,  283,  297,  284,  298,  270,
      299,  300,  285,  295,  302,  286,  287,  290,  303,  291,

      304,  305,  310,  292,  306,  293,  296,  307,  309,  311,
      312,  297,  313,  298,  299,  314,  300,  315,  302,  316,
      317,  318,  326,  303,  304,  320,  305,  310,  306,  321,
      322,  307,  309,  311,  323,  312,  324,  313,  325,  314,
      329,  332,  315,  316,  317,  330,  318,  326,  331,  320,
      333,  334,  337,  321,  322,  335,  336,  339,  323,  340,
      324,  341,  325,  342,  343,  329,  332,  345,  350,  330,
      346,  348,  331,  349,  333,  351,  334,  337,  352,  335,
      336,  353,  339,  340,  354,  355,  341,  342,  343,  356,
      357,  363,  345,  350,  346,  348,  358,  349,  359,  361,

      351,  364,  352,  365,  366,  353,  367,  257,  368,  354,
      355,  369,  370,  372,  356,  357,  363,  373,  374,  377,
      358,  375,  359,  361,  378,  364,  379,  365,  366,  380,
      382,  367,  368,  381,  383,  369,  370,  384,  372,  385,
      386,  373,  387,  374,  377,  375,  388,  389,  392,  378,
      379,  393,  245,  396,  380,  382,  397,  381,  383,  399,
      403,  384,  401,  385,  404,  386,  387,  406,  407,  411,
      388,  389,  408,  392,  409,  410,  393,  396,  412,  413,
      397,  414,  415,  417,  399,  403,  401,  418,  419,  404,
      420,  406,  421,  407,  411,  423,  408,  424,  409,  410,

      425,  426,  428,  412,  413,  427,  414,  415,  417,  429,
      430,  431,  418,  419,  420,  432,  433,  421,  434,  437,
      423,  436,  424,  438,  425,  439,  426,  428,  440,  427,
      441,  442,  443,  429,  430,  431,  444,  239,  445,  447,
      432,  433,  448,  434,  437,  436,  449,  450,  438,  451,
      439,  452,  440,  455,  441,  442,  443,  456,  457,  458,
      459,  444,  445,  460,  447,  461,  465,  448,  462,  463,
      449,  464,  450,  451,  466,  452,  467,  468,  455,  469,
      472,  456,  473,  457,  458,  459,  474,  460,  476,  477,
      461,  465,  462,  463,  478,  464,  480,  481,  466,  483,

      467,  484,  468,  469,  472,  485,  473,  487,  488,  489,
      474,  235,  476,  233,  477,  230,  204,  226,  478,  207,
      480,  481,  204,  483,  199,  484,  198,  195,  183,  485,
      171,  170,  487,  488,  489,   43,  156,   43,   43,   43,
       47,  146,   47,   47,   47,   55,  137,   55,   58,   58,
       40,  133,   40,   40,   40,  203,  203,  203,  203,  203,
      129,  126,  121,  120,   54,   41,   89,   88,   84,   83,
       57,   56,   46,   39,  490,    3,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,

      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490
    } ;

static yyconst flex_int16_t yy_chk[1050] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    8,    8,  485,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    9,   17,   18,   17,    9,

       22,   18,   18,   21,  481,   21,   25,   17,   27,  478,
       21,   28,  474,   29,  470,   17,   32,   22,   35,  469,
        9,   26,   24,  448,    9,   22,   44,   21,   24,   21,
       25,   24,   17,   27,   21,   33,   28,   29,   26,   17,
       32,   22,   35,    8,    8,    8,   26,   24,   30,   31,
       44,   30,   24,   34,   34,   24,   31,  447,   42,   45,
       33,   51,   26,   52,  440,   59,   55,   60,  428,   31,
       55,   55,   30,   62,   31,   30,   63,   66,   34,   34,
       64,   31,   42,   45,  414,  408,   51,  396,   52,   59,
      393,  391,   60,   31,  389,  386,  385,   62,  382,  380,

      363,   63,   66,  357,   64,  348,  346,   42,   43,   43,
       65,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       49,   67,   49,   68,   65,   69,   70,   71,  333,   72,
       73,   49,   74,  330,   75,   76,  323,   77,   78,   49,
       71,   79,   81,   82,  312,   67,   86,   80,   68,   69,
       70,   80,   71,   72,   73,   80,   49,   74,   75,   87,
       76,   77,   78,   49,   71,   79,   81,   82,   43,   43,
       43,   86,   80,   89,   93,   94,   80,   95,   97,  105,
       80,   98,   89,  107,   87,  101,  102,  103,  106,  109,

       89,   95,  110,  111,  311,  112,  113,  114,  117,   93,
       94,  115,   95,   97,  105,   98,  114,   89,  107,  101,
      102,  103,  106,  109,   89,   95,  110,  118,  111,  112,
      113,  119,  114,  117,  120,  115,  121,  122,  123,  125,
      114,  121,  126,  128,  303,  129,  130,  292,  131,  132,
      136,  118,  133,  134,  135,  137,  119,  138,  139,  120,
      121,  122,  123,  125,  140,  121,  126,  143,  128,  129,
      144,  130,  131,  145,  132,  136,  133,  134,  135,  137,
      146,  138,  139,  147,  285,  148,  149,  150,  140,  151,
      152,  153,  143,  155,  156,  144,  158,  159,  145,  160,

      278,  161,  162,  163,  146,  165,  166,  170,  147,  148,
      149,  150,  168,  151,  171,  152,  153,  174,  155,  156,
      158,  159,  175,  176,  160,  161,  162,  178,  163,  165,
      179,  166,  170,  181,  273,  182,  168,  183,  171,  184,
      190,  174,  185,  186,  187,  188,  175,  176,  189,  192,
      193,  178,  194,  198,  179,  195,  196,  197,  181,  182,
      199,  183,  201,  202,  184,  190,  185,  186,  187,  188,
      205,  207,  189,  192,  193,  208,  210,  194,  198,  195,
      196,  197,  212,  213,  199,  214,  201,  202,  217,  218,
      272,  219,  220,  254,  221,  205,  207,  223,  224,  208,

      225,  210,  226,  250,  227,  228,  212,  213,  229,  230,
      214,  231,  242,  217,  218,  219,  232,  220,  221,  233,
      235,  223,  224,  236,  237,  225,  238,  226,  227,  228,
      239,  240,  229,  241,  230,  239,  231,  242,  243,  248,
      232,  244,  245,  233,  235,  247,  249,  236,  237,  252,
      238,  253,  256,  257,  239,  240,  258,  241,  262,  239,
      263,  266,  268,  243,  248,  244,  245,  269,  279,  247,
      249,  270,  271,  274,  252,  275,  253,  256,  257,  276,
      258,  277,  280,  262,  263,  266,  281,  268,  282,  246,
      283,  284,  269,  279,  286,  270,  271,  274,  287,  275,

      288,  289,  294,  276,  290,  277,  280,  291,  293,  295,
      296,  281,  297,  282,  283,  298,  284,  299,  286,  300,
      301,  302,  310,  287,  288,  304,  289,  294,  290,  305,
      306,  291,  293,  295,  307,  296,  308,  297,  309,  298,
      314,  317,  299,  300,  301,  315,  302,  310,  316,  304,
      318,  319,  322,  305,  306,  320,  321,  324,  307,  325,
      308,  326,  309,  327,  328,  314,  317,  331,  336,  315,
      332,  334,  316,  335,  318,  337,  319,  322,  338,  320,
      321,  339,  324,  325,  340,  341,  326,  327,  328,  342,
      343,  349,  331,  336,  332,  334,  344,  335,  345,  347,

      337,  350,  338,  351,  352,  339,  353,  234,  354,  340,
      341,  355,  356,  358,  342,  343,  349,  360,  361,  364,
      344,  362,  345,  347,  365,  350,  366,  351,  352,  367,
      370,  353,  354,  369,  371,  355,  356,  372,  358,  373,
      374,  360,  375,  361,  364,  362,  376,  379,  383,  365,
      366,  384,  222,  387,  367,  370,  388,  369,  371,  390,
      394,  372,  392,  373,  395,  374,  375,  397,  398,  403,
      376,  379,  399,  383,  401,  402,  384,  387,  404,  405,
      388,  406,  407,  409,  390,  394,  392,  410,  411,  395,
      412,  397,  413,  398,  403,  415,  399,  416,  401,  402,

      417,  418,  420,  404,  405,  419,  406,  407,  409,  421,
      422,  424,  410,  411,  412,  425,  426,  413,  427,  430,
      415,  429,  416,  431,  417,  432,  418,  420,  433,  419,
      435,  436,  437,  421,  422,  424,  438,  215,  439,  441,
      425,  426,  442,  427,  430,  429,  443,  444,  431,  445,
      432,  446,  433,  452,  435,  436,  437,  453,  454,  455,
      456,  438,  439,  457,  441,  458,  463,  442,  459,  461,
      443,  462,  444,  445,  464,  446,  465,  466,  452,  468,
      471,  453,  472,  454,  455,  456,  473,  457,  475,  476,
      458,  463,  459,  461,  477,  462,  479,  480,  464,  482,

      465,  483,  466,  468,  471,  484,  472,  486,  487,  488,
      473,  211,  475,  209,  476,  206,  203,  200,  477,  180,
      479,  480,  177,  482,  173,  483,  172,  169,  154,  484,
      142,  141,  486,  487,  488,  491,  127,  491,  491,  491,
      492,  116,  492,  492,  492,  493,  108,  493,  494,  494,
      495,  104,  495,  495,  495,  496,  496,  496,  496,  496,
      100,   96,   92,   91,   90,   85,   48,   47,   40,   37,
       20,   19,   11,    7,    3,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,

      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "trabalho.lex"
#line 853 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 82 "trabalho.lex"


#line 1043 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 491 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 976 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 84 "trabalho.lex"
{}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 85 "trabalho.lex"
{}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 86 "trabalho.lex"
{}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 88 "trabalho.lex"
{ return TK_CTE_INT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 89 "trabalho.lex"
{ return TK_CTE_DOUBLE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 90 "trabalho.lex"
{ return TK_CTE_FLOAT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 91 "trabalho.lex"
{ return TK_CTE_CHAR; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 92 "trabalho.lex"
{ return TK_CTE_STRING; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 93 "trabalho.lex"
{ return TK_CTE_BOOL_TRUE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 94 "trabalho.lex"
{ return TK_CTE_BOOL_FALSE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 96 "trabalho.lex"
{ return TK_INT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 97 "trabalho.lex"
{ return TK_DOUBLE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 98 "trabalho.lex"
{ return TK_FLOAT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 99 "trabalho.lex"
{ return TK_CHAR; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 100 "trabalho.lex"
{ return TK_STRING; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 101 "trabalho.lex"
{ return TK_BOOL; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 102 "trabalho.lex"
{ return TK_VOID; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 104 "trabalho.lex"
{ return TK_ATRIBUICAO; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 106 "trabalho.lex"
{ return TK_MAIN; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 107 "trabalho.lex"
{ return TK_COMECA_BLOCO; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 108 "trabalho.lex"
{ return TK_TERMINA_BLOCO; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 109 "trabalho.lex"
{ return TK_TERMINA_MAIN; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 110 "trabalho.lex"
{ return TK_COMECA_FUNCAO; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 111 "trabalho.lex"
{ return TK_TERMINA_FUNCAO; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 113 "trabalho.lex"
{ return TK_IF; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 114 "trabalho.lex"
{ return TK_ELSE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 115 "trabalho.lex"
{ return TK_FOR; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 116 "trabalho.lex"
{ return TK_DO; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 117 "trabalho.lex"
{ return TK_WHILE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 118 "trabalho.lex"
{ return TK_SWITCH; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 119 "trabalho.lex"
{ return TK_CASE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 120 "trabalho.lex"
{ return TK_DEFAULT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 122 "trabalho.lex"
{ return TK_RETURN; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 124 "trabalho.lex"
{ return TK_SCAN; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 125 "trabalho.lex"
{ return TK_PRINT; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 128 "trabalho.lex"
{ return TK_OR; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 129 "trabalho.lex"
{ return TK_AND; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 130 "trabalho.lex"
{ return TK_NOT; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 132 "trabalho.lex"
{ return TK_COMP_MAIOR; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 133 "trabalho.lex"
{ return TK_COMP_MENOR; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 134 "trabalho.lex"
{ return TK_COMP_MAIOR_IGUAL; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 135 "trabalho.lex"
{ return TK_COMP_MENOR_IGUAL; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 136 "trabalho.lex"
{ return TK_COMP_IGUAL; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 137 "trabalho.lex"
{ return TK_COMP_DIFF; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 139 "trabalho.lex"
{ return TK_ADICAO; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 140 "trabalho.lex"
{ return TK_SUBTRACAO; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 141 "trabalho.lex"
{ return TK_MULTIPLICACAO; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 142 "trabalho.lex"
{ return TK_DIVISAO; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 143 "trabalho.lex"
{ return TK_MODULO; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 145 "trabalho.lex"
{ return TK_PROTOTIPO; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 147 "trabalho.lex"
{ return TK_NULL; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 148 "trabalho.lex"
{ return TK_BREAK; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 149 "trabalho.lex"
{ return TK_DECLARAR_VAR; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 150 "trabalho.lex"
{ return TK_AS; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 152 "trabalho.lex"
{return TK_INICIO;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 153 "trabalho.lex"
{return TK_INCLUDE;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 154 "trabalho.lex"
{ return TK_BIB_INCLUDE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 156 "trabalho.lex"
{return TK_ID;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 158 "trabalho.lex"
{ return *yytext; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 160 "trabalho.lex"
ECHO;
	YY_BREAK
#line 1428 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 491 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 491 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 490);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 160 "trabalho.lex"



