
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 60
#define YY_END_OF_BUFFER 61
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[491] =
    {   0,
        0,    0,   61,   59,    1,    2,   38,   59,   59,   49,
       59,   59,   47,   45,   46,   48,    4,   40,   18,   39,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   20,   59,   21,   44,
        0,    8,    0,    0,    0,   37,    0,    0,    4,    6,
        4,    0,   42,   57,    0,   43,   41,   58,   58,   58,
       54,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   36,    8,    0,    0,    7,    5,    0,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   10,

       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,    0,    5,   58,
       58,   58,   58,   58,    9,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,    0,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   31,   58,   58,
       58,   58,   58,   58,   11,   58,   58,   13,   58,   58,
       58,    0,   58,   58,   58,   58,    0,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   50,   58,   58,   58,   58,   58,    0,   58,   58,

       58,   58,    0,    3,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   16,   58,   58,   58,
       58,   58,   58,    0,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   56,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,    0,   58,   58,   58,
       58,   58,   58,   58,   12,   58,   58,   58,   32,   53,
       14,   58,   58,   26,   15,   58,   17,   58,   58,    0,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,    0,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,

       58,    0,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   34,   58,   58,   58,   58,    0,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   35,   58,
       58,   58,    0,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,    0,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   24,   58,
        0,   58,   58,   58,   58,   58,   58,   28,   58,   58,
       58,   58,   58,    0,   58,   58,   23,   51,   58,   58,
       52,   58,   58,   58,   58,    0,   58,   58,   58,   58,
        0,   58,   58,   58,    0,   58,   58,   58,   58,   19,

       58,   58,   58,    0,   58,   58,   58,   58,   58,   58,
       58,    0,   58,   58,   58,   58,   58,   58,   58,    0,
       58,   58,   24,   58,   58,   58,   58,    0,   58,   58,
       58,   58,   58,   25,    0,   58,   58,   58,   58,   58,
        0,   58,   58,   58,   58,   58,    0,   58,   29,   22,
       27,   58,    0,   58,   58,    0,   58,   58,    0,   30,
       58,    0,   58,    0,   58,    0,   33,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   55,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,    1,   20,
       21,   22,    1,    1,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   32,   46,   32,
        1,    1,    1,    1,   47,    1,   48,   49,   50,   51,

       52,   53,   54,   55,   56,   32,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,   67,   68,   69,   32,
       70,   32,   71,   72,   73,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[74] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    1,    4,    1,
        3,    3,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[497] =
    {   0,
        0,    0,  973,  974,  974,  974,  951,   73,   46,  974,
      962,    0,  974,  974,  974,  974,   79,   82,  949,  948,
       75,   74,    0,   60,   86,   68,   77,   83,   89,   73,
       86,  118,   94,  128,  125,   99,  974,  896,  974,  974,
      961,  974,  147,  202,  121,  974,  956,  946,  208,  974,
      131,  132,  974,  974,  146,  974,  974,    0,  130,  139,
        0,  129,  143,  148,  134,  135,  145,  162,  174,  187,
      194,  205,  189,  191,  212,  198,  212,  207,  201,  209,
      249,  210,  204,  974,  974,  958,  227,  974,  258,  941,
      915,  914,  233,  236,  238,  252,  913,  255,  244,    0,

      912,  253,  249,  249,  911,  252,  252,  258,  910,  261,
      253,  275,  258,  266,  296,  261,  909,  273,  278,  294,
      292,  283,  296,  312,    0,  290,  295,  908,  311,  307,
      310,  301,  317,  306,  310,  318,  322,  321,  312,  325,
      322,  907,  949,  335,  341,  344,  340,  336,  334,  341,
      343,  351,  357,  347,  897,  355,  360,    0,  355,  351,
      362,  360,  358,  371,    0,  363,  376,    0,  371,  892,
      381,  366,  887,  882,  377,  384,  922,  385,  377,  877,
      381,  385,  380,  391,  403,  397,  398,  395,  398,  405,
      405,    0,  394,  406,  412,  412,  411,  414,  423,  415,

      875,  423,  918,  974,  429,  872,  435,  430,  871,  428,
      442,  870,  439,  429,  449,  869,    0,  454,  453,  446,
      456,  448,  864,  443,  450,  458,  458,  447,  452,  466,
      472,  467,  467,    0,  861,  473,  479,  479,  477,  480,
      473,  486,  492,  500,  489,  485,  902,  489,  506,  494,
      857,  506,  507,  856,    0,  512,  512,  508,    0,    0,
        0,  520,  510,    0,    0,  511,    0,  526,  530,  522,
      520,  765,  749,  528,  529,  527,  529,  699,  540,  533,
      552,  546,  537,  551,  679,  549,  559,  551,  562,  554,
      557,  622,  557,  573,  560,  573,  578,  566,  578,  566,

      569,  591,  590,  576,  581,  578,  580,  577,  589,  597,
      531,  487,    0,  601,  591,  601,  613,  592,  615,  606,
      612,  618,  453,  626,  618,  631,  620,  620,    0,  295,
      627,  614,  335,  626,  621,  634,  637,  635,  630,  649,
      646,  655,  654,  644,  645,  289,  647,  252,  665,  659,
      661,  655,  667,  658,  664,  669,  204,  678,    0,  666,
      676,  665,  203,  683,  685,  677,  685,    0,  679,  698,
      682,  693,  696,  707,  699,  704,    0,    0,  699,  202,
        0,  237,  712,  719,  193,  233,  704,  711,  186,  718,
      188,  716,  147,  728,  726,  145,  718,  730,  720,  974,

      721,  722,  739,  744,  745,  747,  744,  144,  750,  748,
      760,  751,  757,  142,  762,  763,  753,  768,  755,  772,
      767,  763,    0,  769,  778,  776,  781,  182,  776,  793,
      792,  792,  782,    0,  786,  790,  781,  803,  799,  136,
      806,  806,  797,  813,  808,  805,  175,  131,    0,    0,
        0,  813,  806,  818,  823,  823,  820,  831,  818,    0,
      821,  826,  841,  834,  830,  841,    0,  832,  142,  117,
      829,  839,  838,  116,  838,  853,  850,  114,  851,  849,
      109,  844,  854,  853,  104,  872,  870,  875,  974,  974,
      927,  932,  935,  937,  942,  947

    } ;

static yyconst flex_int16_t yy_def[497] =
    {   0,
      490,    1,  490,  490,  490,  490,  490,  491,  490,  490,
      490,  492,  490,  490,  490,  490,  490,  493,  490,  490,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  490,  490,  490,  490,
      495,  490,  495,  491,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  493,  490,  490,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  490,  490,  495,  490,  490,  490,  490,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,

      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  490,  490,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  490,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  490,  494,  494,  494,  494,  496,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  490,  494,  494,

      494,  494,  496,  490,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  490,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  490,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  490,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  490,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,

      494,  490,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  490,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  490,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  490,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      490,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  490,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  490,  494,  494,  494,  494,
      490,  494,  494,  494,  490,  494,  494,  494,  494,  490,

      494,  494,  494,  490,  494,  494,  494,  494,  494,  494,
      494,  490,  494,  494,  494,  494,  494,  494,  494,  490,
      494,  494,  494,  494,  494,  494,  494,  490,  494,  494,
      494,  494,  494,  494,  490,  494,  494,  494,  494,  494,
      490,  494,  494,  494,  494,  494,  490,  494,  494,  494,
      494,  494,  490,  494,  494,  490,  494,  494,  490,  494,
      494,  490,  494,  490,  494,  490,  494,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,    0,
      490,  490,  490,  490,  490,  490

    } ;

static yyconst flex_int16_t yy_nxt[1048] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
        4,    4,   13,   14,    4,   15,    4,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   23,   25,   23,   26,
       27,   23,   23,   28,   29,   30,   23,   23,   23,   23,
       31,   32,   33,   34,   35,   36,   23,   21,   22,   23,
       24,   23,   25,   23,   26,   27,   23,   28,   29,   30,
       23,   23,   23,   23,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   41,   41,   45,   41,   41,   42,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   43,
       41,   41,   41,   41,   41,   48,   62,   49,   52,   64,

       45,   69,   53,   54,   68,   71,   50,  486,   59,   73,
       60,   72,  482,   63,   51,   61,   65,  479,   70,  475,
      471,   62,   66,   64,   74,   67,   69,   75,   68,   79,
       71,   50,   59,   73,   60,   83,   72,   63,   51,   61,
       76,   65,   70,   41,   41,   41,   66,   77,   74,   67,
       80,   75,   85,   79,   81,   82,  470,   87,   50,   83,
       78,   90,   52,   91,   92,   76,  490,   54,   93,   94,
       95,   98,   77,   96,   97,   80,   86,  454,  453,   81,
       82,   87,  446,   50,   78,  435,   90,   91,  422,   92,
      416,  405,   93,  402,   94,   95,   98,   96,   97,  400,

      100,   86,   41,   41,   99,   41,   41,   42,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   43,   41,
       41,   41,   41,   41,   48,  100,   49,  101,   99,  102,
      105,  103,  398,  106,  107,   50,  395,  108,  109,  394,
      110,  111,  112,   51,  104,  116,  117,  391,  390,  376,
      371,  101,  118,  102,  105,  122,  103,  106,  123,  107,
       50,  108,  124,  109,  110,  111,  112,   51,  104,  116,
      117,  113,   41,   41,   41,  114,   89,  118,  125,  115,
      122,  128,  135,  123,  129,   50,  137,  124,  131,  132,
      133,  136,  126,  119,  139,  140,  113,  141,  362,  142,

      114,  143,  146,  125,  115,   50,  128,  135,  129,  148,
       50,  137,  131,  132,  133,  136,  126,  119,  139,  140,
      144,  149,  141,  142,  152,  143,  146,  150,  153,  145,
       50,  155,  151,  148,  154,  360,  156,  158,  347,  159,
      160,  344,  161,  162,  166,  144,  149,  163,  152,  164,
      165,  150,  153,  145,  167,  155,  151,  168,  169,  154,
      156,  170,  158,  159,  173,  160,  161,  174,  162,  166,
      175,  163,  176,  164,  165,  177,  178,  179,  167,  180,
      181,  168,  169,  182,  185,  170,  183,  186,  189,  173,
      187,  188,  174,  190,  191,  175,  176,  192,  194,  177,

      178,  179,  193,  180,  195,  181,  197,  208,  182,  185,
      183,  198,  186,  189,  187,  188,  201,  190,  191,  202,
      205,  206,  192,  194,  209,  210,  193,  211,  195,  212,
      218,  197,  208,  213,  214,  198,  215,  216,  217,  219,
      201,  220,  221,  202,  205,  206,  222,  223,  209,  210,
      224,  211,  225,  229,  212,  218,  226,  213,  214,  228,
      215,  216,  217,  219,  231,  220,  232,  221,  234,  235,
      222,  223,  237,  238,  224,  239,  241,  225,  229,  242,
      226,  243,  244,  228,  245,  247,  248,  249,  250,  231,
      232,  251,  234,  252,  235,  253,  237,  238,  254,  338,

      239,  241,  255,  256,  242,  243,  258,  244,  245,  247,
      248,  259,  249,  250,  260,  251,  261,  252,  264,  262,
      253,  265,  266,  254,  263,  267,  255,  256,  268,  269,
      258,  271,  272,  328,  273,  259,  275,  276,  260,  278,
      261,  279,  264,  262,  280,  265,  281,  266,  263,  282,
      267,  283,  268,  269,  284,  271,  285,  272,  273,  286,
      287,  275,  276,  290,  278,  291,  279,  292,  280,  293,
      295,  281,  296,  282,  297,  283,  298,  327,  299,  284,
      300,  285,  302,  286,  287,  303,  305,  290,  304,  291,
      306,  292,  307,  293,  309,  295,  296,  310,  312,  297,

      311,  298,  299,  313,  315,  300,  302,  314,  316,  317,
      303,  305,  304,  318,  306,  320,  307,  321,  309,  322,
      323,  324,  310,  312,  311,  325,  326,  329,  313,  315,
      330,  314,  316,  317,  331,  332,  319,  333,  318,  320,
      334,  321,  335,  322,  323,  324,  336,  337,  339,  325,
      340,  326,  329,  341,  330,  342,  343,  345,  331,  346,
      332,  333,  348,  349,  350,  334,  335,  351,  308,  352,
      336,  353,  337,  339,  340,  354,  355,  356,  341,  342,
      343,  357,  345,  346,  358,  359,  348,  349,  361,  350,
      363,  367,  351,  352,  364,  353,  365,  366,  368,  369,

      354,  355,  356,  370,  372,  374,  357,  373,  358,  359,
      375,  377,  361,  378,  380,  363,  367,  379,  364,  381,
      365,  366,  368,  369,  382,  301,  383,  370,  384,  372,
      374,  373,  385,  386,  375,  387,  377,  388,  378,  380,
      389,  379,  392,  381,  393,  294,  396,  397,  399,  382,
      383,  401,  384,  403,  404,  407,  385,  406,  386,  387,
      408,  388,  409,  410,  389,  411,  412,  392,  413,  393,
      396,  397,  414,  399,  415,  401,  417,  418,  403,  404,
      407,  406,  419,  421,  408,  420,  409,  410,  423,  424,
      411,  412,  425,  413,  426,  289,  427,  414,  428,  415,

      429,  417,  418,  430,  431,  432,  433,  419,  421,  420,
      434,  288,  436,  423,  424,  437,  425,  438,  439,  426,
      427,  440,  441,  428,  429,  442,  443,  430,  431,  444,
      432,  433,  445,  447,  448,  434,  436,  449,  450,  455,
      437,  451,  438,  439,  452,  440,  441,  456,  457,  442,
      443,  458,  459,  461,  444,  460,  445,  462,  447,  448,
      463,  449,  464,  450,  455,  451,  465,  468,  452,  466,
      467,  456,  469,  457,  472,  473,  458,  459,  461,  460,
      474,  462,  476,  477,  463,  478,  464,  480,  481,  483,
      484,  465,  468,  466,  467,  485,  469,  487,  472,  473,

      488,  489,  277,  274,  474,  270,  476,  257,  477,  478,
      246,  480,  481,  483,  484,  240,  236,  233,  230,  485,
      204,  227,  487,  207,  204,  488,  489,   44,  200,   44,
       44,   44,   47,  199,   47,   47,   47,   55,  196,   55,
       58,   58,   41,  184,   41,   41,   41,  203,  203,  203,
      203,  203,  172,  171,  157,  147,  138,  134,  130,  127,
      121,  120,   54,   42,   89,   88,   85,   84,   57,   56,
       46,   40,  490,    3,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,

      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490
    } ;

static yyconst flex_int16_t yy_chk[1048] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    8,    8,    9,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,   17,   22,   17,   18,   24,

        9,   27,   18,   18,   26,   28,   17,  485,   21,   30,
       21,   29,  481,   22,   17,   21,   25,  478,   27,  474,
      470,   22,   25,   24,   31,   25,   27,   31,   26,   33,
       28,   17,   21,   30,   21,   36,   29,   22,   17,   21,
       32,   25,   27,    8,    8,    8,   25,   32,   31,   25,
       34,   31,   43,   33,   35,   35,  469,   45,   51,   36,
       32,   52,   55,   59,   60,   32,   55,   55,   62,   63,
       64,   67,   32,   65,   66,   34,   43,  448,  447,   35,
       35,   45,  440,   51,   32,  428,   52,   59,  414,   60,
      408,  396,   62,  393,   63,   64,   67,   65,   66,  391,

       69,   43,   44,   44,   68,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   49,   69,   49,   70,   68,   71,
       73,   72,  389,   74,   75,   49,  386,   76,   77,  385,
       78,   79,   80,   49,   72,   82,   83,  382,  380,  363,
      357,   70,   87,   71,   73,   93,   72,   74,   94,   75,
       49,   76,   95,   77,   78,   79,   80,   49,   72,   82,
       83,   81,   44,   44,   44,   81,   89,   87,   96,   81,
       93,   98,  106,   94,   99,   89,  108,   95,  102,  103,
      104,  107,   96,   89,  110,  111,   81,  112,  348,  113,

       81,  114,  116,   96,   81,  119,   98,  106,   99,  118,
       89,  108,  102,  103,  104,  107,   96,   89,  110,  111,
      115,  120,  112,  113,  122,  114,  116,  121,  123,  115,
      119,  126,  121,  118,  124,  346,  127,  129,  333,  130,
      131,  330,  132,  133,  137,  115,  120,  134,  122,  135,
      136,  121,  123,  115,  138,  126,  121,  139,  140,  124,
      127,  141,  129,  130,  144,  131,  132,  145,  133,  137,
      146,  134,  147,  135,  136,  148,  149,  150,  138,  151,
      152,  139,  140,  153,  156,  141,  154,  157,  161,  144,
      159,  160,  145,  162,  163,  146,  147,  164,  167,  148,

      149,  150,  166,  151,  169,  152,  171,  181,  153,  156,
      154,  172,  157,  161,  159,  160,  175,  162,  163,  176,
      178,  179,  164,  167,  182,  183,  166,  184,  169,  185,
      191,  171,  181,  186,  187,  172,  188,  189,  190,  193,
      175,  194,  195,  176,  178,  179,  196,  197,  182,  183,
      198,  184,  199,  205,  185,  191,  200,  186,  187,  202,
      188,  189,  190,  193,  207,  194,  208,  195,  210,  211,
      196,  197,  213,  214,  198,  215,  218,  199,  205,  219,
      200,  220,  221,  202,  222,  224,  225,  226,  227,  207,
      208,  228,  210,  229,  211,  230,  213,  214,  231,  323,

      215,  218,  232,  233,  219,  220,  236,  221,  222,  224,
      225,  237,  226,  227,  238,  228,  239,  229,  241,  240,
      230,  242,  243,  231,  240,  244,  232,  233,  245,  246,
      236,  248,  249,  312,  250,  237,  252,  253,  238,  256,
      239,  257,  241,  240,  258,  242,  262,  243,  240,  263,
      244,  266,  245,  246,  268,  248,  269,  249,  250,  270,
      271,  252,  253,  274,  256,  275,  257,  276,  258,  277,
      279,  262,  280,  263,  281,  266,  282,  311,  283,  268,
      284,  269,  286,  270,  271,  287,  289,  274,  288,  275,
      290,  276,  291,  277,  293,  279,  280,  294,  296,  281,

      295,  282,  283,  297,  299,  284,  286,  298,  300,  301,
      287,  289,  288,  302,  290,  304,  291,  305,  293,  306,
      307,  308,  294,  296,  295,  309,  310,  314,  297,  299,
      315,  298,  300,  301,  316,  317,  303,  318,  302,  304,
      319,  305,  320,  306,  307,  308,  321,  322,  324,  309,
      325,  310,  314,  326,  315,  327,  328,  331,  316,  332,
      317,  318,  334,  335,  336,  319,  320,  337,  292,  338,
      321,  339,  322,  324,  325,  340,  341,  342,  326,  327,
      328,  343,  331,  332,  344,  345,  334,  335,  347,  336,
      349,  353,  337,  338,  350,  339,  351,  352,  354,  355,

      340,  341,  342,  356,  358,  361,  343,  360,  344,  345,
      362,  364,  347,  365,  367,  349,  353,  366,  350,  369,
      351,  352,  354,  355,  370,  285,  371,  356,  372,  358,
      361,  360,  373,  374,  362,  375,  364,  376,  365,  367,
      379,  366,  383,  369,  384,  278,  387,  388,  390,  370,
      371,  392,  372,  394,  395,  398,  373,  397,  374,  375,
      399,  376,  401,  402,  379,  403,  404,  383,  405,  384,
      387,  388,  406,  390,  407,  392,  409,  410,  394,  395,
      398,  397,  411,  413,  399,  412,  401,  402,  415,  416,
      403,  404,  417,  405,  418,  273,  419,  406,  420,  407,

      421,  409,  410,  422,  424,  425,  426,  411,  413,  412,
      427,  272,  429,  415,  416,  430,  417,  431,  432,  418,
      419,  433,  435,  420,  421,  436,  437,  422,  424,  438,
      425,  426,  439,  441,  442,  427,  429,  443,  444,  452,
      430,  445,  431,  432,  446,  433,  435,  453,  454,  436,
      437,  455,  456,  458,  438,  457,  439,  459,  441,  442,
      461,  443,  462,  444,  452,  445,  463,  466,  446,  464,
      465,  453,  468,  454,  471,  472,  455,  456,  458,  457,
      473,  459,  475,  476,  461,  477,  462,  479,  480,  482,
      483,  463,  466,  464,  465,  484,  468,  486,  471,  472,

      487,  488,  254,  251,  473,  247,  475,  235,  476,  477,
      223,  479,  480,  482,  483,  216,  212,  209,  206,  484,
      203,  201,  486,  180,  177,  487,  488,  491,  174,  491,
      491,  491,  492,  173,  492,  492,  492,  493,  170,  493,
      494,  494,  495,  155,  495,  495,  495,  496,  496,  496,
      496,  496,  143,  142,  128,  117,  109,  105,  101,   97,
       92,   91,   90,   86,   48,   47,   41,   38,   20,   19,
       11,    7,    3,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,

      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "trabalho.lex"
#line 853 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 82 "trabalho.lex"


#line 1043 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 491 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 974 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 84 "trabalho.lex"
{}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 85 "trabalho.lex"
{}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 86 "trabalho.lex"
{return TK_COMENTARIO;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 88 "trabalho.lex"
{ return TK_CTE_INT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 89 "trabalho.lex"
{ return TK_CTE_DOUBLE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 90 "trabalho.lex"
{ return TK_CTE_FLOAT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 91 "trabalho.lex"
{ return TK_CTE_CHAR; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 92 "trabalho.lex"
{ return TK_CTE_STRING; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 93 "trabalho.lex"
{ return TK_CTE_BOOL_TRUE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 94 "trabalho.lex"
{ return TK_CTE_BOOL_FALSE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 96 "trabalho.lex"
{ return TK_INT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 97 "trabalho.lex"
{ return TK_DOUBLE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 98 "trabalho.lex"
{ return TK_FLOAT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 99 "trabalho.lex"
{ return TK_CHAR; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 100 "trabalho.lex"
{ return TK_STRING; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 101 "trabalho.lex"
{ return TK_BOOL; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 102 "trabalho.lex"
{ return TK_VOID; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 104 "trabalho.lex"
{ return TK_ATRIBUICAO; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 106 "trabalho.lex"
{ return TK_MAIN; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 107 "trabalho.lex"
{ return TK_COMECA_BLOCO; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 108 "trabalho.lex"
{ return TK_TERMINA_BLOCO; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 109 "trabalho.lex"
{ return TK_TERMINA_MAIN; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 110 "trabalho.lex"
{ return TK_COMECA_FUNCAO; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 111 "trabalho.lex"
{ return TK_TERMINA_FUNCAO; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 113 "trabalho.lex"
{ return TK_IF; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 114 "trabalho.lex"
{ return TK_ELSE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 115 "trabalho.lex"
{ return TK_FOR; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 116 "trabalho.lex"
{ return TK_DO; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 117 "trabalho.lex"
{ return TK_WHILE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 118 "trabalho.lex"
{ return TK_SWITCH; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 119 "trabalho.lex"
{ return TK_CASE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 120 "trabalho.lex"
{ return TK_DEFAULT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 122 "trabalho.lex"
{ return TK_RETURN; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 124 "trabalho.lex"
{ return TK_SCAN; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 125 "trabalho.lex"
{ return TK_PRINT; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 128 "trabalho.lex"
{ return TK_OR; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 129 "trabalho.lex"
{ return TK_AND; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 130 "trabalho.lex"
{ return TK_NOT; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 132 "trabalho.lex"
{ return TK_COMP_MAIOR; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 133 "trabalho.lex"
{ return TK_COMP_MENOR; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 134 "trabalho.lex"
{ return TK_COMP_MAIOR_IGUAL; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 135 "trabalho.lex"
{ return TK_COMP_MENOR_IGUAL; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 136 "trabalho.lex"
{ return TK_COMP_IGUAL; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 137 "trabalho.lex"
{ return TK_COMP_DIFF; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 139 "trabalho.lex"
{ return TK_ADICAO; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 140 "trabalho.lex"
{ return TK_SUBTRACAO; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 141 "trabalho.lex"
{ return TK_MULTIPLICACAO; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 142 "trabalho.lex"
{ return TK_DIVISAO; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 143 "trabalho.lex"
{ return TK_MODULO; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 145 "trabalho.lex"
{ return TK_PROTOTIPO; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 147 "trabalho.lex"
{ return TK_NULL; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 148 "trabalho.lex"
{}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 149 "trabalho.lex"
{ return TK_DECLARAR_VAR; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 150 "trabalho.lex"
{ return TK_AS; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 152 "trabalho.lex"
{return TK_INICIO;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 153 "trabalho.lex"
{return TK_INCLUDE;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 154 "trabalho.lex"
{ return TK_BIB_INCLUDE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 156 "trabalho.lex"
{return TK_ID;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 158 "trabalho.lex"
{ return *yytext; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 160 "trabalho.lex"
ECHO;
	YY_BREAK
#line 1428 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 491 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 491 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 490);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 160 "trabalho.lex"


