
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 58
#define YY_END_OF_BUFFER 59
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[477] =
    {   0,
        0,    0,   59,   57,    1,    2,   36,   57,   57,   47,
       57,   57,   45,   43,   44,   46,    4,   38,   18,   37,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   20,   57,   21,   42,    0,
        8,    0,    0,    0,   35,    0,    0,    4,    6,    4,
        0,   40,   55,    0,   41,   39,   56,   56,   56,   52,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       34,    8,    0,    0,    7,    5,    0,   56,   56,   56,
       56,   56,   56,   56,   10,   56,   56,   56,   56,   56,

       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,    0,    5,   56,   56,   56,   56,   56,    9,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
        0,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   11,   56,   56,   13,   56,
       56,   56,    0,   56,   56,   56,   56,    0,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   48,   56,   56,   56,   56,   56,    0,   56,   56,
       56,   56,    0,    3,   56,   56,   56,   56,   56,   56,

       56,   56,   56,   56,   56,   16,   56,   56,   56,   56,
       56,   56,    0,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   54,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,    0,   56,   56,   56,   56,   56,
       56,   56,   12,   56,   56,   56,   51,   14,   56,   56,
       26,   15,   56,   17,   56,   56,    0,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,    0,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,    0,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   32,

       56,   56,   56,   56,    0,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   33,   56,   56,   56,    0,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,    0,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   24,   56,    0,   56,   56,
       56,   56,   56,   56,   28,   56,   56,   56,   56,   56,
        0,   56,   56,   23,   49,   56,   56,   50,   56,   56,
       56,   56,    0,   56,   56,   56,   56,    0,   56,   56,
       56,    0,   56,   56,   56,   56,   19,   56,   56,   56,
        0,   56,   56,   56,   56,   56,   56,   56,    0,   56,

       56,   24,   56,   56,   56,   56,    0,   56,   56,   56,
       56,   56,   56,    0,   56,   56,   56,   56,   56,   25,
        0,   56,   56,   56,   56,   56,    0,   56,   56,   56,
       56,   56,    0,   56,   29,   22,   27,   56,    0,   56,
       56,    0,   56,   56,    0,   30,   56,    0,   56,    0,
       56,    0,   31,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   53,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,    1,   20,
       21,   22,    1,    1,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   32,   46,   32,
        1,    1,    1,    1,   47,    1,   48,   49,   50,   51,

       52,   53,   54,   55,   56,   32,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,   67,   68,   69,   32,
       70,   32,   71,   72,   73,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[74] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    1,    4,    1,
        3,    3,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[483] =
    {   0,
        0,    0,  948,  949,  949,  949,  926,   73,   46,  949,
      937,    0,  949,  949,  949,  949,   79,   82,  924,  923,
       75,   74,    0,   60,   75,   77,   82,   94,   73,   84,
      118,   77,  105,  121,   88,  949,  871,  949,  949,  936,
      949,  148,  203,  118,  949,  931,  921,  139,  949,  129,
      129,  949,  949,  143,  949,  949,    0,  128,  137,    0,
      129,  143,  148,  134,  162,  145,  165,  191,  201,  189,
      189,  206,  193,  207,  202,  196,  204,  216,  206,  202,
      949,  949,  933,  220,  949,  251,  916,  890,  889,  225,
      229,  233,  240,  888,    0,  887,  242,  241,  242,  886,

      232,  245,  260,  885,  252,  248,  270,  253,  260,  273,
      255,  884,  263,  273,  275,  276,  271,  283,  299,    0,
      283,  285,  296,  299,  290,  306,  293,  298,  306,  319,
      310,  299,  312,  308,  883,  925,  320,  325,  327,  324,
      320,  318,  327,  328,  336,  344,  333,  881,  344,  340,
      337,  353,  348,  346,  359,    0,  350,  364,    0,  358,
      880,  367,  349,  879,  870,  358,  365,  909,  367,  359,
      860,  381,  370,  367,  378,  390,  383,  379,  383,  390,
      400,    0,  383,  394,  400,  400,  399,  401,  402,  398,
      855,  404,  895,  949,  418,  850,  416,  412,  847,  409,

      424,  842,  410,  431,  839,    0,  438,  436,  430,  440,
      432,  837,  427,  435,  445,  445,  433,  438,  451,  455,
      448,  448,    0,  836,  453,  453,  451,  458,  449,  461,
      468,  479,  470,  467,  878,  471,  489,  477,  832,  489,
      492,  830,    0,  497,  496,  491,    0,    0,  502,  491,
        0,    0,  491,    0,  504,  508,  499,  498,  793,  716,
      504,  506,  503,  505,  674,  516,  509,  530,  526,  517,
      532,  646,  531,  539,  531,  546,  537,  539,  639,  538,
      552,  538,  554,  555,  542,  558,  545,  549,  563,  470,
      552,  557,  553,  362,  552,  564,  574,  347,  296,    0,

      580,  569,  579,  592,  571,  594,  585,  588,  594,  591,
      604,  597,  605,  595,  597,    0,  287,  604,  592,  295,
      602,  599,  605,  612,  605,  609,  617,  625,  634,  631,
      623,  624,  247,  625,  243,  644,  637,  638,  635,  646,
      636,  642,  644,  233,  653,    0,  641,  655,  641,  203,
      661,  663,  652,  669,    0,  663,  679,  663,  673,  675,
      686,  679,  685,    0,    0,  202,  197,    0,  229,  683,
      694,  188,  197,  679,  686,  699,  695,  188,  693,  147,
      701,  701,  144,  694,  704,  696,  949,  699,  700,  717,
      725,  725,  728,  729,  143,  730,  729,  739,  729,  740,

      142,    0,  741,  730,  744,  733,  745,  742,  736,  742,
      752,  752,  755,  183,  752,  763,  764,  764,  755,    0,
      761,  767,  758,  779,  775,  136,  779,  783,  773,  791,
      786,  781,  177,  133,    0,    0,    0,  791,  781,  793,
      796,  796,  793,  807,  794,    0,  795,  799,  813,  805,
      805,  821,    0,  811,  153,  125,  808,  819,  814,  117,
      816,  831,  830,  116,  830,  828,  114,  823,  834,  829,
      104,  837,  843,  848,  949,  949,  900,  905,  908,  910,
      915,  920
    } ;

static yyconst flex_int16_t yy_def[483] =
    {   0,
      476,    1,  476,  476,  476,  476,  476,  477,  476,  476,
      476,  478,  476,  476,  476,  476,  476,  479,  476,  476,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  476,  476,  476,  476,  481,
      476,  481,  477,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  479,  476,  476,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      476,  476,  481,  476,  476,  476,  476,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,

      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  476,  476,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      476,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  476,  480,  480,  480,  480,  482,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  476,  480,  480,
      480,  480,  482,  476,  480,  480,  480,  480,  480,  480,

      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  476,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  476,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  476,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  476,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  476,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,

      480,  480,  480,  480,  476,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  476,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  476,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  476,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      476,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  476,  480,  480,  480,  480,  476,  480,  480,
      480,  476,  480,  480,  480,  480,  476,  480,  480,  480,
      476,  480,  480,  480,  480,  480,  480,  480,  476,  480,

      480,  480,  480,  480,  480,  480,  476,  480,  480,  480,
      480,  480,  480,  476,  480,  480,  480,  480,  480,  480,
      476,  480,  480,  480,  480,  480,  476,  480,  480,  480,
      480,  480,  476,  480,  480,  480,  480,  480,  476,  480,
      480,  476,  480,  480,  476,  480,  480,  476,  480,  476,
      480,  476,  480,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,    0,  476,  476,  476,  476,
      476,  476
    } ;

static yyconst flex_int16_t yy_nxt[1023] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
        4,    4,   13,   14,    4,   15,    4,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   23,   25,   23,   23,
       26,   23,   23,   27,   28,   29,   23,   23,   23,   23,
       30,   31,   32,   33,   34,   35,   23,   21,   22,   23,
       24,   23,   25,   23,   23,   26,   23,   27,   28,   29,
       23,   23,   23,   23,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   40,   40,   44,   40,   40,   41,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   42,
       40,   40,   40,   40,   40,   47,   61,   48,   51,   63,

       44,   66,   52,   53,   68,   64,   49,  472,   58,   70,
       59,   65,   76,   62,   50,   60,   69,  468,   67,  465,
      461,   61,   71,   63,   80,   72,   66,   77,  457,   68,
       64,   49,   58,   70,   59,   65,   76,   62,   50,   60,
       73,   69,   67,   40,   40,   40,   71,   74,   80,   72,
       78,   79,   77,   82,   84,   47,   49,   48,   87,   51,
       75,   88,   89,  476,   53,   73,   49,  456,   90,   91,
       92,   95,   74,   93,   50,   78,   79,   83,   84,  440,
      439,   49,  432,   87,   75,   88,  421,   89,  409,  403,
      392,   49,   90,  389,   91,   92,   95,   93,   50,  387,

      382,   94,   83,   40,   40,   96,   40,   40,   41,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   42,
       40,   40,   40,   40,   40,   94,   97,   98,  102,   96,
      100,  101,  103,  104,  381,  105,  106,  107,  108,  378,
       99,  111,  109,  377,  112,  113,  110,  117,  376,  363,
       97,  118,   98,  102,  100,  101,  103,  119,  104,  105,
      106,  107,  128,  108,   99,  111,  120,  109,  112,   86,
      113,  110,  117,   40,   40,   40,  118,  124,   49,  358,
      121,  125,  119,  126,  129,  132,  114,  128,  130,  349,
      133,  120,  134,  347,  135,  136,  139,  137,  334,  141,

       49,  124,  142,   49,  121,  125,  138,  126,  129,  132,
      114,  143,  145,  130,  133,  146,  144,  134,  135,  136,
      139,  147,  137,  141,  148,   49,  149,  142,  150,  151,
      138,  152,  153,  331,  154,  143,  145,  155,  156,  146,
      144,  157,  315,  158,  159,  160,  147,  161,  148,  164,
      149,  165,  150,  166,  151,  152,  167,  153,  154,  168,
      169,  155,  156,  170,  171,  172,  157,  158,  159,  160,
      173,  161,  174,  176,  164,  177,  165,  178,  166,  179,
      167,  180,  181,  168,  169,  182,  184,  170,  171,  183,
      172,  185,  187,  314,  188,  173,  174,  191,  176,  177,

      192,  178,  195,  196,  179,  180,  181,  198,  310,  199,
      182,  184,  200,  183,  201,  185,  202,  187,  188,  203,
      204,  191,  205,  206,  192,  207,  195,  196,  208,  209,
      210,  214,  198,  199,  211,  212,  200,  213,  201,  215,
      217,  202,  218,  203,  204,  220,  205,  206,  221,  223,
      207,  224,  208,  209,  226,  210,  214,  227,  211,  212,
      229,  213,  230,  215,  217,  231,  232,  218,  233,  235,
      220,  236,  221,  223,  237,  238,  224,  239,  226,  240,
      241,  242,  227,  243,  244,  229,  246,  230,  247,  231,
      248,  232,  233,  235,  251,  236,  252,  249,  253,  237,

      238,  239,  250,  240,  254,  241,  242,  243,  244,  255,
      246,  256,  247,  258,  248,  259,  306,  260,  251,  262,
      252,  249,  263,  253,  265,  266,  250,  267,  268,  254,
      269,  270,  271,  255,  272,  256,  273,  258,  274,  277,
      259,  260,  278,  279,  262,  280,  282,  263,  283,  265,
      266,  267,  284,  268,  269,  270,  285,  271,  286,  272,
      273,  287,  274,  277,  289,  290,  278,  279,  291,  280,
      292,  282,  283,  293,  294,  296,  297,  284,  298,  299,
      300,  285,  286,  301,  302,  305,  287,  303,  289,  304,
      290,  307,  291,  308,  309,  292,  311,  293,  294,  296,

      312,  297,  298,  313,  299,  300,  316,  301,  317,  302,
      305,  303,  318,  304,  319,  307,  320,  308,  309,  321,
      311,  322,  323,  324,  312,  325,  326,  328,  313,  327,
      329,  316,  317,  330,  332,  337,  318,  333,  335,  319,
      320,  336,  338,  341,  321,  322,  323,  339,  324,  325,
      340,  326,  328,  327,  329,  342,  343,  330,  344,  332,
      337,  333,  335,  345,  346,  336,  348,  338,  341,  350,
      354,  339,  351,  352,  340,  353,  355,  356,  357,  359,
      342,  343,  360,  344,  361,  295,  362,  345,  346,  364,
      348,  365,  288,  366,  350,  354,  351,  352,  367,  353,

      355,  356,  357,  368,  359,  369,  360,  370,  371,  361,
      362,  372,  373,  379,  364,  374,  365,  366,  375,  380,
      281,  383,  384,  367,  385,  386,  390,  368,  388,  391,
      369,  370,  371,  393,  394,  372,  395,  373,  379,  374,
      396,  397,  375,  398,  380,  383,  384,  399,  400,  385,
      386,  390,  388,  401,  391,  402,  404,  393,  405,  394,
      395,  406,  276,  407,  396,  397,  408,  410,  398,  411,
      412,  414,  399,  400,  413,  415,  416,  417,  401,  418,
      402,  404,  419,  405,  420,  423,  406,  407,  422,  424,
      425,  408,  410,  411,  426,  412,  414,  427,  413,  415,

      416,  417,  428,  429,  418,  430,  433,  419,  431,  420,
      423,  434,  422,  435,  424,  425,  436,  441,  426,  437,
      438,  427,  442,  443,  444,  445,  428,  429,  446,  447,
      430,  433,  431,  448,  449,  450,  434,  435,  451,  275,
      452,  436,  441,  437,  438,  453,  442,  454,  443,  444,
      445,  455,  446,  458,  447,  459,  460,  448,  449,  450,
      462,  463,  473,  451,  452,  464,  466,  467,  469,  453,
      470,  471,  454,  474,  475,  455,  264,  458,  261,  459,
      460,  257,  245,  234,  462,  228,  463,  473,  225,  464,
      466,  467,  469,  222,  470,  471,  219,  194,  474,  475,

       43,  216,   43,   43,   43,   46,  197,   46,   46,   46,
       54,  194,   54,   57,   57,   40,  190,   40,   40,   40,
      193,  193,  193,  193,  193,  189,  186,  175,  163,  162,
      140,  131,  127,  123,  122,  116,  115,   53,   41,   86,
       85,   82,   81,   56,   55,   45,   39,  476,    3,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,

      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476
    } ;

static yyconst flex_int16_t yy_chk[1023] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    8,    8,    9,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,   17,   22,   17,   18,   24,

        9,   26,   18,   18,   27,   25,   17,  471,   21,   29,
       21,   25,   32,   22,   17,   21,   28,  467,   26,  464,
      460,   22,   30,   24,   35,   30,   26,   33,  456,   27,
       25,   17,   21,   29,   21,   25,   32,   22,   17,   21,
       31,   28,   26,    8,    8,    8,   30,   31,   35,   30,
       34,   34,   33,   42,   44,   48,   50,   48,   51,   54,
       31,   58,   59,   54,   54,   31,   48,  455,   61,   62,
       63,   66,   31,   64,   48,   34,   34,   42,   44,  434,
      433,   50,  426,   51,   31,   58,  414,   59,  401,  395,
      383,   48,   61,  380,   62,   63,   66,   64,   48,  378,

      373,   65,   42,   43,   43,   67,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   65,   68,   69,   72,   67,
       70,   71,   73,   74,  372,   75,   76,   77,   78,  369,
       69,   79,   78,  367,   80,   84,   78,   90,  366,  350,
       68,   91,   69,   72,   70,   71,   73,   92,   74,   75,
       76,   77,  101,   78,   69,   79,   93,   78,   80,   86,
       84,   78,   90,   43,   43,   43,   91,   97,   86,  344,
       93,   98,   92,   99,  102,  105,   86,  101,  103,  335,
      106,   93,  107,  333,  108,  109,  111,  110,  320,  113,

      114,   97,  115,   86,   93,   98,  110,   99,  102,  105,
       86,  116,  117,  103,  106,  118,  116,  107,  108,  109,
      111,  119,  110,  113,  121,  114,  122,  115,  123,  124,
      110,  125,  126,  317,  127,  116,  117,  128,  129,  118,
      116,  130,  299,  131,  132,  133,  119,  134,  121,  137,
      122,  138,  123,  139,  124,  125,  140,  126,  127,  141,
      142,  128,  129,  143,  144,  145,  130,  131,  132,  133,
      146,  134,  147,  149,  137,  150,  138,  151,  139,  152,
      140,  153,  154,  141,  142,  155,  158,  143,  144,  157,
      145,  160,  162,  298,  163,  146,  147,  166,  149,  150,

      167,  151,  169,  170,  152,  153,  154,  172,  294,  173,
      155,  158,  174,  157,  175,  160,  176,  162,  163,  177,
      178,  166,  179,  180,  167,  181,  169,  170,  183,  184,
      185,  189,  172,  173,  186,  187,  174,  188,  175,  190,
      192,  176,  195,  177,  178,  197,  179,  180,  198,  200,
      181,  201,  183,  184,  203,  185,  189,  204,  186,  187,
      207,  188,  208,  190,  192,  209,  210,  195,  211,  213,
      197,  214,  198,  200,  215,  216,  201,  217,  203,  218,
      219,  220,  204,  221,  222,  207,  225,  208,  226,  209,
      227,  210,  211,  213,  229,  214,  230,  228,  231,  215,

      216,  217,  228,  218,  232,  219,  220,  221,  222,  233,
      225,  234,  226,  236,  227,  237,  290,  238,  229,  240,
      230,  228,  241,  231,  244,  245,  228,  246,  249,  232,
      250,  253,  255,  233,  256,  234,  257,  236,  258,  261,
      237,  238,  262,  263,  240,  264,  266,  241,  267,  244,
      245,  246,  268,  249,  250,  253,  269,  255,  270,  256,
      257,  271,  258,  261,  273,  274,  262,  263,  275,  264,
      276,  266,  267,  277,  278,  280,  281,  268,  282,  283,
      284,  269,  270,  285,  286,  289,  271,  287,  273,  288,
      274,  291,  275,  292,  293,  276,  295,  277,  278,  280,

      296,  281,  282,  297,  283,  284,  301,  285,  302,  286,
      289,  287,  303,  288,  304,  291,  305,  292,  293,  306,
      295,  307,  308,  309,  296,  310,  311,  313,  297,  312,
      314,  301,  302,  315,  318,  323,  303,  319,  321,  304,
      305,  322,  324,  327,  306,  307,  308,  325,  309,  310,
      326,  311,  313,  312,  314,  328,  329,  315,  330,  318,
      323,  319,  321,  331,  332,  322,  334,  324,  327,  336,
      340,  325,  337,  338,  326,  339,  341,  342,  343,  345,
      328,  329,  347,  330,  348,  279,  349,  331,  332,  351,
      334,  352,  272,  353,  336,  340,  337,  338,  354,  339,

      341,  342,  343,  356,  345,  357,  347,  358,  359,  348,
      349,  360,  361,  370,  351,  362,  352,  353,  363,  371,
      265,  374,  375,  354,  376,  377,  381,  356,  379,  382,
      357,  358,  359,  384,  385,  360,  386,  361,  370,  362,
      388,  389,  363,  390,  371,  374,  375,  391,  392,  376,
      377,  381,  379,  393,  382,  394,  396,  384,  397,  385,
      386,  398,  260,  399,  388,  389,  400,  403,  390,  404,
      405,  407,  391,  392,  406,  408,  409,  410,  393,  411,
      394,  396,  412,  397,  413,  416,  398,  399,  415,  417,
      418,  400,  403,  404,  419,  405,  407,  421,  406,  408,

      409,  410,  422,  423,  411,  424,  427,  412,  425,  413,
      416,  428,  415,  429,  417,  418,  430,  438,  419,  431,
      432,  421,  439,  440,  441,  442,  422,  423,  443,  444,
      424,  427,  425,  445,  447,  448,  428,  429,  449,  259,
      450,  430,  438,  431,  432,  451,  439,  452,  440,  441,
      442,  454,  443,  457,  444,  458,  459,  445,  447,  448,
      461,  462,  472,  449,  450,  463,  465,  466,  468,  451,
      469,  470,  452,  473,  474,  454,  242,  457,  239,  458,
      459,  235,  224,  212,  461,  205,  462,  472,  202,  463,
      465,  466,  468,  199,  469,  470,  196,  193,  473,  474,

      477,  191,  477,  477,  477,  478,  171,  478,  478,  478,
      479,  168,  479,  480,  480,  481,  165,  481,  481,  481,
      482,  482,  482,  482,  482,  164,  161,  148,  136,  135,
      112,  104,  100,   96,   94,   89,   88,   87,   83,   47,
       46,   40,   37,   20,   19,   11,    7,    3,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,

      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "trabalho.lex"
#line 844 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 80 "trabalho.lex"


#line 1034 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 477 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 949 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 82 "trabalho.lex"
{}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 83 "trabalho.lex"
{}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 84 "trabalho.lex"
{return TK_COMENTARIO;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 86 "trabalho.lex"
{ return TK_CTE_INT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 87 "trabalho.lex"
{ return TK_CTE_DOUBLE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 88 "trabalho.lex"
{ return TK_CTE_FLOAT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 89 "trabalho.lex"
{ return TK_CTE_CHAR; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 90 "trabalho.lex"
{ return TK_CTE_STRING; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 91 "trabalho.lex"
{ return TK_CTE_BOOL_TRUE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 92 "trabalho.lex"
{ return TK_CTE_BOOL_FALSE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 94 "trabalho.lex"
{ return TK_INT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 95 "trabalho.lex"
{ return TK_DOUBLE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 96 "trabalho.lex"
{ return TK_FLOAT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 97 "trabalho.lex"
{ return TK_CHAR; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 98 "trabalho.lex"
{ return TK_STRING; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 99 "trabalho.lex"
{ return TK_BOOL; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 100 "trabalho.lex"
{ return TK_VOID; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 102 "trabalho.lex"
{ return TK_ATRIBUICAO; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 104 "trabalho.lex"
{ return TK_MAIN; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 105 "trabalho.lex"
{ return TK_COMECA_BLOCO; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 106 "trabalho.lex"
{ return TK_TERMINA_BLOCO; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 107 "trabalho.lex"
{ return TK_TERMINA_MAIN; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 108 "trabalho.lex"
{ return TK_COMECA_FUNCAO; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 109 "trabalho.lex"
{ return TK_TERMINA_FUNCAO; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 111 "trabalho.lex"
{}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 112 "trabalho.lex"
{}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 113 "trabalho.lex"
{}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 114 "trabalho.lex"
{}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 115 "trabalho.lex"
{}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 116 "trabalho.lex"
{}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 118 "trabalho.lex"
{}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 120 "trabalho.lex"
{}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 121 "trabalho.lex"
{}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 124 "trabalho.lex"
{ return TK_OR; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 125 "trabalho.lex"
{ return TK_AND; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 126 "trabalho.lex"
{ return TK_NOT; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 128 "trabalho.lex"
{ return TK_COMP_MAIOR; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 129 "trabalho.lex"
{ return TK_COMP_MENOR; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 130 "trabalho.lex"
{ return TK_COMP_MAIOR_IGUAL; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 131 "trabalho.lex"
{ return TK_COMP_MENOR_IGUAL; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 132 "trabalho.lex"
{ return TK_COMP_IGUAL; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 133 "trabalho.lex"
{ return TK_COMP_DIFF; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 135 "trabalho.lex"
{ return TK_ADICAO; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 136 "trabalho.lex"
{ return TK_SUBTRACAO; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 137 "trabalho.lex"
{ return TK_MULTIPLICACAO; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 138 "trabalho.lex"
{ return TK_DIVISAO; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 139 "trabalho.lex"
{ return TK_MODULO; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 141 "trabalho.lex"
{ return TK_PROTOTIPO; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 143 "trabalho.lex"
{}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 144 "trabalho.lex"
{}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 145 "trabalho.lex"
{ return TK_DECLARAR_VAR; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 146 "trabalho.lex"
{ return TK_AS; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 148 "trabalho.lex"
{return TK_INICIO;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 149 "trabalho.lex"
{return TK_INCLUDE;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 150 "trabalho.lex"
{ return TK_BIB_INCLUDE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 152 "trabalho.lex"
{return TK_ID;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 154 "trabalho.lex"
{ return *yytext; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 156 "trabalho.lex"
ECHO;
	YY_BREAK
#line 1409 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 477 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 477 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 476);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 156 "trabalho.lex"


